---
output:
  reprex::reprex_document:
    venue: "gh"
    advertise: FALSE
    session_info: TRUE
    style: TRUE
    comment: "#;-)"
    tidyverse_quiet: FALSE
    std_out_err: TRUE
knit: reprex::reprex_render
---

# WonderCat

```{r}
library(tidyverse)
library(shiny)
# library(httr)
library(httr2)
library(jsonlite)
library(dplyr)
library(bslib)
library(DT)
library(ggplot2)
# library(ggraph)
# library(igraph)
library(plotly)
# library(treemap)
library(treemapify)
library(visNetwork)
library(WikidataQueryServiceR)
library(leaflet)

print (getwd())
# Import functions.
source(paste0(getwd(), '/main/functions.R'))

dataframe <- call_api_and_build_dataframe("https://env-1120817.us.reclaim.cloud/wp-json/wp/v2/user-experience")
wikiResp <- get_wikidata(dataframe)

dataframe <- inner_join(wikiResp %>% select(title, QID), dataframe, by = "QID", multiple = "all") %>%
  unique()

wikiData <- dataframe %>% select(QID) %>% 
  inner_join(wikiResp, by = "QID", multiple = "all") %>% 
  group_by(QID) %>% nest(data = c(genreLabel, pubDate)) %>% distinct()
```

## API Call

### Call API (httr2) and Build Dataframe
```{r}
url <- "https://env-1120817.us.reclaim.cloud/wp-json/wp/v2/user-experience"

req <- request(url)

resp <- req_perform(req) %>% resp_body_json()
headers <- req |> req_perform() |> resp_headers()
page_info <- req |> req_perform() |> resp_headers("x-wp-totalpages")
total_pages <- as.numeric(page_info[[1]])

resps <- req |>
  req_perform_iterative(
    next_req = iterate_with_offset(
      param_name = "page",
      resp_pages = \(resp) resp_body_json(resp)$info$pages
    ),
    max_reqs = total_pages
  )

data <- vector("list", length = length(resps))

for (i in 1:length(resps)) {
  data$i <- i
  data[[i]] <- resps[[i]] %>% resp_body_json(check_type = FALSE, simplifyVector = TRUE) %>%  
    unnest(c(benefit, experience, technology, acf), names_sep = '.', keep_empty = TRUE) %>%
    rename('benefit' = contains('benefit.name')) %>% # Renames benefit.name (entry is present) to benefit (no entry).
    unnest(benefit, acf.wikidata, keep_empty = TRUE) %>% 
    select(
      id, author, date, 
      benefit, experience.name, technology.name, 
      acf.title_of_creative_work, acf.feature, starts_with('acf.wikidata-qid'), starts_with('entities')
    ) %>% 
    unnest(entities, keep_empty = TRUE) # Drill down to Wiki claims.
    # unnest(id, keep_empty = TRUE) %>%
}

dataframe <- do.call(rbind, data)


colnames(dataframe) <- c('id', 'author', 'date', 'benefit', 'experience', 'technology', 'title', 'text','QID')

dataframe$date <- as.POSIXct(dataframe$date, format = "%Y-%m-%d")

dataframe$date <- as.Date(dataframe$date, format = '%y%m%d')

dataframe %>% head()
print (dim(dataframe))
dataframe <- head(dataframe, -1)
print (dim(dataframe))
```

### Wikidata
```{r}
QIDS <- dataframe %>% filter(grepl('Q\\d+', QID))
QIDS <- lapply('wd:', paste0, QIDS[['QID']])
QIDS <- paste(unlist(QIDS), collapse = ' ')

query <- paste0("
  SELECT DISTINCT
        ?item ?itemLabel ?pubDate ?genreLabel
        ?countryOriginLabel ?coordinates

    WHERE {
        VALUES ?item {",QIDS,"}

        ?item wdt:P31 ?instanceof.
        OPTIONAL {?item wdt:P136 ?genre}.
        OPTIONAL {?item wdt:P577 ?pubDate}.
        ?item wdt:P495 ?countryOrigin .
        ?countryOrigin wdt:P625 ?coordinates.
    
        SERVICE wikibase:label { bd:serviceParam wikibase:language 'en,en'. }}")
        
wiki_resp <- query_wikidata(query)
names(wiki_resp)[names(wiki_resp) == 'item'] <- 'QID'
wiki_resp$QID <- sub('.*/entity/(Q\\d+)', '\\1', wiki_resp$QID)

# Clean up dates.
wiki_resp$pubDate <- sub('(\\d{4}-\\d{2}-\\d{2}).*', '\\1', wiki_resp$pubDate)

# Clean up longitude and latitude.
wiki_resp$lon <- sub('Point\\(([-]?\\d+\\.?\\d+)\\s([-]?\\d+\\.?\\d+)\\)', '\\1', wiki_resp$coordinates)
wiki_resp$lon <- as.numeric(wiki_resp$lon)
wiki_resp$lat <- sub('Point\\(([-]?\\d+\\.?\\d+)\\s([-]?\\d+\\.?\\d+)\\)', '\\2', wiki_resp$coordinates)
wiki_resp$lat <- as.numeric(wiki_resp$lat)
```

## Visualizations

### Leaflet
```{r}
leaflet(data = wikiData %>% distinct(QID, .keep_all = TRUE)) %>% 
  addTiles() %>%
  addMarkers(label = ~title, clusterOptions = markerClusterOptions())
```

### Bar Plot
```{r}
bar_data <- dataframe %>% count(technology, name = 'count') %>% mutate(decile = ntile(count, 10))
#  %>%
#   filter(between(decile, 8, 10))

bar_data

p <- bar_data |>
      ggplot(aes(x = n, y = technology, fill = technology)) +
      geom_bar(stat = "identity")

ggplotly(p)
```

### Quantile Test for Bar Plot
```{r}


quantile_filter <- function(dataframe, column, min_value, max_value){
    
    min_quantile_value <- quantile(dataframe %>% pull(all_of(column)), min_value)
    max_quantile_value <- quantile(dataframe %>% pull(all_of(column)), max_value)
    
    #iris %>% filter(.data[[column]] < quantile_value)
    dataframe %>% filter(.data[[column]] %in% (min_quantile_value:max_quantile_value))
    
  }

# input$quantile = 
less_iris <- quantile_filter(bar_data, "n", 0.5, 1)
```

### Tree Map
```{r}
treeData <-  dataframe %>% 
  group_by(title, experience) %>% summarize(count = n()) %>%
  mutate(decile = ntile(count, 10))
#treemap(treeData, index = c("title", "experience"), vSize="count", type="index")

ggplot(treeData, aes(area = count, label = title, fill = experience, subgroup = experience)) + 
  geom_treemap() +
  geom_treemap_subgroup_border() +
  geom_treemap_text(fontface = "italic", colour = "black", place = "topleft", grow = FALSE) +
  geom_treemap_subgroup_border() +
  geom_treemap_subgroup_text(place = "centre", grow = T, alpha = 0.3, colour = "black", fontface = "italic", min.size = 0)
```

```{r}
treemap(treeData,
        index=c("experience","title"),
        vSize="count",
        vColor = "experience",
        type = "categorical",
        # formatting options:
        #palette = brewer.pal(n = 5, name = "Accent"),
        align.labels=list(
          c("left", "top"), 
          c("right", "bottom")
        ),     
        border.col = "white",
        bg.labels = 255,
        position.legend = "none")
```

### Network (subset)
```{r}
# Network Function for Building from Subset
create_network_data <- function(dataframe, columnOne, columnTwo){
  
  # Create links from columns: source -> technology -> experience.
  links = dataframe %>% select(columnOne, columnTwo)
  colnames(links) = c('from', 'to')

  # Bind links dataframe and remove any rows with NA.
  links = links %>%
    filter(grepl('\\w+', from)) %>%
    filter(grepl('\\w+', to))

  # Create co-occurrence for link weights.
  links = links %>% group_by(from, to) %>% summarize(weight = n())

  # Create nodes from links and rename column name.
  nodeOne = dataframe[columnOne]
  colnames(nodeOne) = 'label'
  nodeOne$category = columnOne

  nodeTwo = dataframe[columnTwo]
  colnames(nodeTwo) = 'label'
  nodeTwo$category = columnTwo

  # Combine all nodes and remove whitespace entries.
  nodes = rbind(nodeOne, nodeTwo) %>% filter(grepl('\\w+', label))

  # Create node size variable
  nodes = nodes %>% group_by(label, category) %>% summarize(size = n())

  # Remove duplicate nodes.
  nodes = nodes[!duplicated(nodes),] %>% data.frame()

  # Create column ID usind nodes index as value.
  nodes$id = rownames(nodes)

  # Replace "labels" in links to nodes "id" value.
  links$from = nodes$id[ match( unlist(links$from), nodes$label)]
  links$to = nodes$id[ match( unlist(links$to), nodes$label)]

  # Set Styling.
  # We'll start by adding new node and edge attributes to our dataframes. 
  vis.nodes <- nodes
  vis.links <- links

  vis.nodes$shape  <- "dot"  
  vis.nodes$shadow <- TRUE # Nodes will drop shadow
  vis.nodes$title  <- vis.nodes$label # Text on click
  vis.nodes$label <- vis.nodes$label # Node label
  vis.nodes$size   <- 40 #vis.nodes$size # Node size
  vis.nodes$borderWidth <- 2 # Node border width

  # c("slategrey", "tomato", "gold")
  colorMap = c(technology = "slategrey", experience = "tomato", title = "gold", author = "#94797E")
  vis.nodes$color.background <- colorMap[vis.nodes$category]


  vis.nodes$color.border <- "black"
  vis.nodes$color.highlight.background <- "orange"
  vis.nodes$color.highlight.border <- "darkred"

  #vis.links$width <- links$weight # line width
  vis.links$color <- "gray"    # line color  
  vis.links$arrows <- "to" # arrows: 'from', 'to', or 'middle'
  vis.links$smooth <- TRUE    # should the edges be curved?
  vis.links$shadow <- FALSE    # edge shadow

  return(list(nodes = vis.nodes, links = vis.links))
}


columnOne <- "experience"
columnTwo <- "title"

create_network_data(data, columnOne, columnTwo)
```


### Network
```{r}

# Create links from columns: source -> technology -> experience.
title_tech = dataframe %>% select(title, technology)
colnames(title_tech) = c('from', 'to')

tech_exp = dataframe %>% select(technology, experience)
colnames(tech_exp) = c('from', 'to')

exp_user = dataframe %>% select(experience, author)
colnames(exp_user) = c("from", "to")

# Bind links dataframe and remove any rows with NA.
links = rbind(title_tech, tech_exp, exp_user)  %>%
  filter(grepl('\\w+', from)) %>%
  filter(grepl('\\w+', to))

# Create co-occurrence for link weights.
links = links %>% group_by(from, to) %>% summarize(weight = n())

# Create nodes from links and rename column name.
sources = dataframe['title']
colnames(sources) = 'label'
sources$category = 'source'

technologies = dataframe['technology']
colnames(technologies) = 'label'
technologies$category = 'technology'

experiences = dataframe['experience']
colnames(experiences) = 'label'
experiences$category = 'experience'

users = dataframe["author"]
colnames(users) = "label"
users$category = "author"

# Combine all nodes and remove whitespace entries.
nodes = rbind(sources, technologies, experiences, users) %>% filter(grepl('\\w+', label))

# Create node size variable
nodes = nodes %>% group_by(label, category) %>% summarize(size = n())

# Remove duplicate nodes.
nodes = nodes[!duplicated(nodes),] %>% data.frame()

# Create column ID usind nodes index as value.
nodes$id = rownames(nodes)

# Replace "labels" in links to nodes "id" value.
links$from = nodes$id[ match( unlist(links$from), nodes$label)]
links$to = nodes$id[ match( unlist(links$to), nodes$label)]

# Remove variables.
rm(title_tech, tech_exp, sources, experiences, technologies, users)

# Set Styling.
# We'll start by adding new node and edge attributes to our dataframes. 
vis.nodes <- nodes
vis.links <- links

vis.nodes$shape  <- "dot"  
vis.nodes$shadow <- TRUE # Nodes will drop shadow
vis.nodes$title  <- vis.nodes$label # Text on click
vis.nodes$label <- vis.nodes$label # Node label
vis.nodes$size   <- vis.nodes$size * 10 # Node size
vis.nodes$borderWidth <- 2 # Node border width

# c("slategrey", "tomato", "gold")
colorMap = c(tecnique = "slategrey", experience = "tomato", source = "gold", author = "#94797E")
vis.nodes$color.background <- colorMap[vis.nodes$category]


vis.nodes$color.border <- "black"
vis.nodes$color.highlight.background <- "orange"
vis.nodes$color.highlight.border <- "darkred"

vis.links$width <- links$weight # line width
vis.links$color <- "gray"    # line color  
vis.links$arrows <- "to" # arrows: 'from', 'to', or 'middle'
vis.links$smooth <- TRUE    # should the edges be curved?
vis.links$shadow <- FALSE    # edge shadow

visnet <- visNetwork(vis.nodes, vis.links)

visOptions(
  visnet,
  highlightNearest = TRUE,
  selectedBy = "label"
)
```

### Network (importing nodes and links)
```{r}
# Import data.
nodes <- read_delim(paste0(getwd(), "/nodes.tsv"))
links <- read_delim(paste0(getwd(), "/links.tsv"))

# Set Styling.
# We'll start by adding new node and edge attributes to our dataframes. 
vis.nodes <- nodes
vis.links <- links

vis.nodes$shape  <- "dot"  
vis.nodes$shadow <- TRUE # Nodes will drop shadow
vis.nodes$title  <- vis.nodes$label # Text on click
vis.nodes$label <- vis.nodes$label # Node label
vis.nodes$size   <- vis.nodes$size * 10 # Node size
vis.nodes$borderWidth <- 2 # Node border width

# c("slategrey", "tomato", "gold")
colorMap = c(tecnique = "slategrey", experience = "tomato", source = "gold", author = "#94797E")
vis.nodes$color.background <- colorMap[vis.nodes$category]


vis.nodes$color.border <- "black"
vis.nodes$color.highlight.background <- "orange"
vis.nodes$color.highlight.border <- "darkred"

vis.links$width <- links$weight # line width
vis.links$color <- "gray"    # line color  
vis.links$arrows <- "to" # arrows: 'from', 'to', or 'middle'
vis.links$smooth <- TRUE    # should the edges be curved?
vis.links$shadow <- FALSE    # edge shadow

visnet <- visNetwork(vis.nodes, vis.links)

visOptions(
  visnet,
  highlightNearest = TRUE,
  selectedBy = "label"
)
```
